<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir));

return array(
    'org\\bovigo\\vfs' => array($vendorDir . '/mikey179/vfsStream/src/main/php'),
    '' => array($vendorDir . '/nfephp-org/nfephp/libs', $vendorDir . '/nfephp-org/nfephp/tests'),
);
